version: "3"

services:
  web:
    container_name: unittest_web
    image: my_nginx
    build:
      context: ./.docker
    ports:
      - 8001:80
    volumes:
      - ./:/app
    links:
      - db
    working_dir: /app

  node:
    container_name: unittest_node
    image: nikolaik/python-nodejs:python3.10-nodejs16-alpine
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www

  db:
    container_name: unittest_db
    image: mysql:5.7
    ports:
      - 8003:3306
    volumes:
      - ./.docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./.docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
      - ./.db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: laravel
